# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d173758326514f9dba92a3762dc44ff30f0583706b8f24c983c099194080faa16e296be2fb800167e7b32f9a9a89bac5941f49e4ff9f7484914082557888bef4

test:
  secret_key_base: 6a4cd2a9b64f9f3e370fee41e14388c87d37fca94c60d144803b08e851376dbd33bccc3712d78b5b5d5ee922137a8e255c18ce88cbd5ba74333082bf457e41d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
